### PR TITLE
Update the User Guide and fix some bugs

### LINKED ISSUE #132: Update UpdateCommand in User Guide

### PR DESCRIPTION
**Pull request by ArtillerySun**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/UpdateCommandParser.java [hunk 1]
```diff
@@ -70,34 +70,45 @@ public UpdateCommand parse(String args) throws ParseException {
...
             updatePersonDescriptor.setAppointment(ParserUtil
                     .parseAppointment(argMultimap.getValue(PREFIX_APPOINTMENT).get()));
+            isUpdated = true;
         }
-        parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)).ifPresent(updatePersonDescriptor::setTags);
-
-        if (!updatePersonDescriptor.isAnyFieldEdited()) {
+        if (!argMultimap.getAllValues(PREFIX_TAG).isEmpty()) {
+            parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)).ifPresent(updatePersonDescriptor::setTags);
+            isUpdated = true;
```
Comment (Jaynon) [inline src/main/java/seedu/address/logic/parser/UpdateCommandParser.java:109]: looks ok

File: src/main/java/seedu/address/logic/parser/UpdateCommandParser.java [hunk 2]
```diff
@@ -70,34 +70,45 @@ public UpdateCommand parse(String args) throws ParseException {
         // Create an UpdatePersonDescriptor from the arguments
         UpdateCommand.UpdatePersonDescriptor updatePersonDescriptor = new UpdatePersonDescriptor();
 
+        boolean isUpdated = false;
         if (argMultimap.getValue(PREFIX_NAME).isPresent()) {
             updatePersonDescriptor.setName(ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get()));
+            isUpdated = true;
         }
         if (argMultimap.getValue(PREFIX_AGE).isPresent()) {
             updatePersonDescriptor.setAge(ParserUtil.parseAge(argMultimap.getValue(PREFIX_AGE).get()));
```
Comment (Jaynon) [inline src/main/java/seedu/address/logic/parser/UpdateCommandParser.java:79]: hmm looks kinda of janky

**Review by Jaynon — APPROVED** [review]
lgtm
